const express = require("express");
const router = express.Router();
const { SuperAdmin } = require('../controller/index')

router.route('/api/addClass').post(SuperAdmin.addClass)
router.route('/api/addStudent').post(SuperAdmin.addStudent)
router.route('/api/addSection').post(SuperAdmin.addSection)
router.route('/api/getClasses').get(SuperAdmin.getClasses)
router.route('/api/getSections').get(SuperAdmin.getSections)
router.route('/api/classData').get(SuperAdmin.classData)
router.route('/api/sectionData/:id').get(SuperAdmin.sectionData)
router.route('/api/singleClass/:id').get(SuperAdmin.singleClass)
router.route('/api/singleSection/:id').get(SuperAdmin.singleSection)
router.route('/api/updateSection/:id').post(SuperAdmin.updateSection)
router.route('/api/deleteSection/:id').delete(SuperAdmin.deleteSection)
router.route('/api/deleteStudent/:id').delete(SuperAdmin.deleteStudent)
router.route('/api/changeSections/:title').get(SuperAdmin.changeSections)
router.route('/api/getStudents/:title').get(SuperAdmin.getStudents)
router.route('/api/submitAttendance').post(SuperAdmin.submitAttendance)
router.route('/api/viewAttendance/:title_s/:title_c').get(SuperAdmin.viewAttendance)
router.route('/api/editAttendance/:date').post(SuperAdmin.editAttendance)
router.route('/api/singleStudent/:id').get(SuperAdmin.singleStudent)
router.route('/api/singleStudentByRoll/:id').get(SuperAdmin.singleStudentByRoll)
router.route('/api/addStudentGrade/').post(SuperAdmin.addStudentGrade)
router.route('/api/getStudentGrades/:id').get(SuperAdmin.getStudentGrades)
router.route('/api/getGradestitles/:id').get(SuperAdmin.getGradestitles)
router.route('/api/getStudentGrades/:id').get(SuperAdmin.getStudentGrades)
router.route('/api/updateGrade/:id').post(SuperAdmin.updateGrade)
router.route('/api/deleteGrade/:id').delete(SuperAdmin.deleteGrade)
router.route('/api/singleGrade/:id').get(SuperAdmin.singleGrade)
router.route('/api/addLecture').post(SuperAdmin.addLecture)
router.route('/api/getTimetable').get(SuperAdmin.getTimetable)
router.route('/api/updateTimetable/:id').post(SuperAdmin.updateTimetable)
router.route('/api/deleteTimetable/:id').delete(SuperAdmin.deleteTimetable)
router.route('/api/updateTimetable/:id').delete(SuperAdmin.updateTimetable)
router.route('/api/singleTimetable/:id').get(SuperAdmin.singleTimetable)
router.route('/api/getDayAttendance/:title_s/:title_c/:id').get(SuperAdmin.getDayAttendance)
router.route('/api/getDataCount').get(SuperAdmin.getDataCount)

module.exports = router